<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="430fe2b6-d060-43cc-aea9-47f8ed81ebd0" name="LCao6@LCAO6-1 2008-11-25 13:55:00" runUser="LCAO6-1\LCao6" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2006">
  <TestRunConfiguration name="Local Test Run" id="4710835c-9ea8-42ba-a19b-7000b8d10914">
    <Description>This is a default test run configuration for a local test run.</Description>
    <Deployment runDeploymentRoot="C:\HPF.FutureState\TestResults\LCao6_LCAO6-1 2008-11-25 13_55_00">
      <DeploymentItem filename="C:\HPF.FutureState\HPF.FutureState.DataAccess\bin\Debug\HPF.FutureState.DataAccess.dll" />
      <DeploymentItem filename="C:\HPF.FutureState\HPF.FutureState.Common\bin\Debug\HPF.FutureState.Common.dll" />
    </Deployment>
    <TestTypeSpecific />
  </TestRunConfiguration>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <Times creation="2008-11-25T13:55:00.4687500-06:00" queuing="2008-11-25T13:55:04.3125000-06:00" start="2008-11-25T13:55:04.6875000-06:00" finish="2008-11-25T13:55:05.9062500-06:00" />
  <TestDefinitions>
    <UnitTest name="TestInsertCallLog" storage="c:\hpf.futurestate\hpf.futurestate.unittest\bin\debug\hpf.futurestate.unittest.dll" id="00543f59-c095-bc25-64f1-628f52cf71d6">
      <Css projectStructure="" iteration="" />
      <Owners>
        <Owner name="" />
      </Owners>
      <Execution id="0d3189fa-8dfa-4fae-b20c-cff4386248ea" />
      <TestMethod codeBase="C:\HPF.FutureState\HPF.FutureState.UnitTest\bin\Debug\HPF.FutureState.UnitTest.dll" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="HPF.FutureState.UnitTest.DataAccess.CallLogTest, HPF.FutureState.UnitTest" name="TestInsertCallLog" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="00543f59-c095-bc25-64f1-628f52cf71d6" executionId="0d3189fa-8dfa-4fae-b20c-cff4386248ea" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="0d3189fa-8dfa-4fae-b20c-cff4386248ea" testId="00543f59-c095-bc25-64f1-628f52cf71d6" testName="TestInsertCallLog" computerName="LCAO6-1" duration="00:00:00.0626937" startTime="2008-11-25T13:55:05.2343750-06:00" endTime="2008-11-25T13:55:05.6718750-06:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d">
      <Output>
        <ErrorInfo>
          <Message>Test method HPF.FutureState.UnitTest.DataAccess.CallLogTest.TestInsertCallLog threw exception:  System.NullReferenceException: Object reference not set to an instance of an object..</Message>
          <StackTrace>    at HPF.FutureState.DataAccess.BaseDAO.get_ConnectionString() in C:\HPF.FutureState\HPF.FutureState.DataAccess\BaseDAO.cs:line 14
   at HPF.FutureState.DataAccess.BaseDAO.CreateConnection() in C:\HPF.FutureState\HPF.FutureState.DataAccess\BaseDAO.cs:line 20
   at HPF.FutureState.DataAccess.CallLogDAO.InsertCallLog(CallLogDTO aCallLog) in C:\HPF.FutureState\HPF.FutureState.DataAccess\CallLogDAO.cs:line 33
   at HPF.FutureState.UnitTest.DataAccess.CallLogTest.InsertACallLog() in C:\HPF.FutureState\HPF.FutureState.UnitTest\DataAccess\CallLogTest.cs:line 86
   at HPF.FutureState.UnitTest.DataAccess.CallLogTest.TestInsertCallLog() in C:\HPF.FutureState\HPF.FutureState.UnitTest\DataAccess\CallLogTest.cs:line 73
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>